<%@ Page Title="" Language="C#" MasterPageFile="~/User.master" AutoEventWireup="true" CodeFile="FeedbackGrid.aspx.cs" Inherits="FeedbackGrid" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="U_ID" DataSourceID="SqlDataSource1" GridLines="Horizontal" 
        Height="199px" Width="795px">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="U_ID" HeaderText="U_ID" ReadOnly="True" 
                SortExpression="U_ID" />
            <asp:BoundField DataField="U_Username" HeaderText="U_Username" 
                SortExpression="U_Username" />
            <asp:BoundField DataField="Feedback" HeaderText="Feedback" 
                SortExpression="Feedback" />
            <asp:BoundField DataField="Suggestion" HeaderText="Suggestion" 
                SortExpression="Suggestion" />
            <asp:BoundField DataField="Ratings" HeaderText="Ratings" 
                SortExpression="Ratings" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RuksarConnectionString %>" 
        SelectCommand="SELECT * FROM [Feedback]" UpdateCommand="Update[Feedback] Set [U_ID]=@U_ID, [U_Username]=@U_Username, [Feedback]=@Feedback, [Suggestion]=@Suggestion, [Ratings]=@Ratings"   DeleteCommand="Delete from [Feedback] where[U_ID]=@U_ID"></asp:SqlDataSource>
</asp:Content>

