<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="ProductGrid.aspx.cs" Inherits="ProductGrid" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <form id="form1" runat="server">
    <h1 align="center"><b>Product Stock</b></h1>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="P_ID" DataSourceID="SqlDataSource1" GridLines="Horizontal">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="P_ID" HeaderText="P_ID" InsertVisible="False" 
                ReadOnly="True" SortExpression="P_ID" />
            <asp:BoundField DataField="P_Name" HeaderText="P_Name" 
                SortExpression="P_Name" />
            <asp:BoundField DataField="P_Price" HeaderText="P_Price" 
                SortExpression="P_Price" />
            <asp:BoundField DataField="P_CatID" HeaderText="P_CatID" 
                SortExpression="P_CatID" />
            <asp:BoundField DataField="P_Quantity" HeaderText="P_Quantity" 
                SortExpression="P_Quantity" />
            <asp:BoundField DataField="P_SizeID" HeaderText="P_SizeID" 
                SortExpression="P_SizeID" />
            <asp:BoundField DataField="P_COD" HeaderText="P_COD" SortExpression="P_COD" />
            <asp:BoundField DataField="PDescription" HeaderText="PDescription" 
                SortExpression="PDescription" />
            <asp:HyperLinkField DataNavigateUrlFields="P_ID" 
                DataNavigateUrlFormatString="AddProduct.aspx?P_ID={0}" 
                HeaderText="Insert-Product" Text="Insert-Product" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RuksarConnectionString %>" 
        SelectCommand="SELECT * FROM [tblProduct]" UpdateCommand="Update [tblProduct] Set[P_Name]=@P_Name, [P_Price]=@P_Price, [P_CatID]=@P_CatID, [P_Quantity]=@P_Quantity, [P_SizeID]=@P_SizeID, [P_COD]=@P_COD, [PDescription]=@PDescription where[P_ID]=@P_ID" DeleteCommand="Delete from [tblProduct] where[P_ID]=@P_ID"></asp:SqlDataSource>
    <br />
    <br />
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="P_IMGID" DataSourceID="SqlDataSource2" GridLines="Horizontal">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="P_IMGID" HeaderText="P_IMGID" InsertVisible="False" 
                ReadOnly="True" SortExpression="P_IMGID" />
            <asp:BoundField DataField="P_ID" HeaderText="P_ID" SortExpression="P_ID" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Extention" HeaderText="Extention" 
                SortExpression="Extention" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RuksarConnectionString %>" 
        SelectCommand="SELECT * FROM [tblProductImages]" UpdateCommand="Update[tblProductImages] Set[P_ID]=@P_ID, [Name]=@Name, [Extention]=@Extention where[P_IMGID]=@P_IMGID" DeleteCommand="Delete from [tblProductImages] where[P_IMGID]=@P_IMGID"></asp:SqlDataSource>
    </form>
    
</asp:Content>
