<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="PurchaseProductGrid.aspx.cs" Inherits="PurchaseProductGrid" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <form id="form1" runat="server">
    <h1 align="center">Purchase List</h1>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" BackColor="White" 
        BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
        DataKeyNames="PurchaseID" DataSourceID="SqlDataSource1" 
        GridLines="Horizontal">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="PurchaseID" HeaderText="PurchaseID" 
                InsertVisible="False" ReadOnly="True" SortExpression="PurchaseID" />
            <asp:BoundField DataField="U_ID" HeaderText="U_ID" SortExpression="U_ID" />
            <asp:BoundField DataField="PIDSizeID" HeaderText="PIDSizeID" 
                SortExpression="PIDSizeID" />
            <asp:BoundField DataField="CartAmount" HeaderText="CartAmount" 
                SortExpression="CartAmount" />
            <asp:BoundField DataField="CartDiscount" HeaderText="CartDiscount" 
                SortExpression="CartDiscount" />
            <asp:BoundField DataField="TotalPayed" HeaderText="TotalPayed" 
                SortExpression="TotalPayed" />
            <asp:BoundField DataField="PaymentType" HeaderText="PaymentType" 
                SortExpression="PaymentType" />
            <asp:BoundField DataField="Status" HeaderText="Status" 
                SortExpression="Status" />
            <asp:BoundField DataField="DateOfPurchase" HeaderText="DateOfPurchase" 
                SortExpression="DateOfPurchase" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Address" HeaderText="Address" 
                SortExpression="Address" />
            <asp:BoundField DataField="Pincode" HeaderText="Pincode" 
                SortExpression="Pincode" />
            <asp:BoundField DataField="MobileNumber" HeaderText="MobileNumber" 
                SortExpression="MobileNumber" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" 
                SortExpression="Quantity" />
            <asp:BoundField DataField="cancel_date" HeaderText="cancel_date" 
                SortExpression="cancel_date" />
            <asp:HyperLinkField DataNavigateUrlFields="PurchaseID" 
                DataNavigateUrlFormatString="CancelOrder.aspx?PurchaseID={0}" 
                HeaderText="Cancel" Text="Cancel" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RuksarConnectionString %>" 
        SelectCommand="SELECT * FROM [tblPurchase]" UpdateCommand="Update [tblPurchase] Set[PurchaseID]=@PurchaseID, [U_ID]=@U_ID, [PIDSizeID]=@PIDSizeID, [CartAmount]=@CartAmount, [CartDiscount]=@CartDiscount, [TotalPayed]=@TotalPayed, [PaymentType]=@PaymentType, [Status]=@Status, [DateOfPurchase]=@DateOfPurchase, [Name]=@Name, [Address]=@Address, [Pincode]=@Pincode,[MobileNumber]=@MobileNumber, [Quantity]=@Quantity, [cancel_date]=@cancel_date  where[PurchaseID]=@PurchaseID" DeleteCommand="Delete from [tblPurchase] where[PurchaseID]=@PurchaseID "></asp:SqlDataSource>
    </form>
</asp:Content>

