<%@ Page Title="" Language="C#" MasterPageFile="~/AdminMaster.master" AutoEventWireup="true" CodeFile="UserGrid1.aspx.cs" Inherits="UserGrid" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <form id="form1" runat="server">
    <h1 align="UserGrid1.">User Profile</h1>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" 
        BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="10" 
        DataKeyNames="U_ID" DataSourceID="SqlDataSource1" GridLines="Horizontal" 
        CellSpacing="10" Font-Bold="True" PageSize="50" Height="100px" 
        HorizontalAlign="Left" Width="100px">
        <AlternatingRowStyle BackColor="#F7F7F7" />
        <Columns>
            <asp:BoundField DataField="U_ID" HeaderText="U_ID" ReadOnly="True" 
                SortExpression="U_ID" />
            <asp:BoundField DataField="U_Name" HeaderText="U_Name" 
                SortExpression="U_Name" />
            <asp:BoundField DataField="U_Username" HeaderText="U_Username" 
                SortExpression="U_Username" />
            <asp:BoundField DataField="U_Email" HeaderText="U_Email" 
                SortExpression="U_Email" />
            <asp:BoundField DataField="U_Password" HeaderText="U_Password" 
                SortExpression="U_Password" />
            <asp:BoundField DataField="U_CPassword" HeaderText="U_CPassword" 
                SortExpression="U_CPassword" />
            <asp:BoundField DataField="U_BDate" HeaderText="U_BDate" 
                SortExpression="U_BDate" />
            <asp:BoundField DataField="U_Gender" HeaderText="U_Gender" 
                SortExpression="U_Gender" />
            <asp:BoundField DataField="U_Phoneno" HeaderText="U_Phoneno" 
                SortExpression="U_Phoneno" />
            <asp:BoundField DataField="U_Address" HeaderText="U_Address" 
                SortExpression="U_Address" />
            <asp:BoundField DataField="U_Usertype" HeaderText="U_Usertype" 
                SortExpression="U_Usertype" />
            <asp:HyperLinkField DataNavigateUrlFields="U_ID" 
                DataNavigateUrlFormatString="UpdateSign-Up.aspx?U_ID={0}" 
                HeaderText="Insert" Text="Insert" />
        </Columns>
        <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
        <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
        <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
        <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
        <SortedAscendingCellStyle BackColor="#F4F4FD" />
        <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
        <SortedDescendingCellStyle BackColor="#D8D8F0" />
        <SortedDescendingHeaderStyle BackColor="#3E3277" />
    </asp:GridView>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RuksarConnectionString %>" 
        SelectCommand="SELECT * FROM [signup]" UpdateCommand="Update [signup] Set[U_Name]=@U_Name, [U_Username]=@U_Username, [U_Email]=@U_Email, [U_Password]=@U_Password, [U_CPassword]=@U_CPassword, [U_BDate]=@U_BDate, [U_Gender]=@U_Gender, [U_Phoneno]=@U_Phoneno, [U_Address]=@U_Address, [U_Usertype]=@U_Usertype where[U_ID]=@U_ID" DeleteCommand="Delete from [signup] where[U_ID]=@U_ID"></asp:SqlDataSource>
        </form>
</asp:Content>

